version: "3.1"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_script_server
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-script_server}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-Admin@123}
      - POSTGRES_DB=${POSTGRES_DB:-script_server}
    volumes:
      - postgres_data:/var/lib/postgresql/script_server/data
    ports:
      - "5461:5432"
    restart: always
volumes:
  postgres_data:

networks:
  strapi:
    name: Strapi
    driver: bridge
